### ISSUE TITLE
Review Microtasks

### ISSUE THREAD

**Issue by vchrombie** [Rashmi-K-A/chaoss-sortinghat#1]
Hi @Rashmi-K-A, thanks for showing interest in applying for the GrimoireLab idea and working on the microtasks as a part of the GSoC program.

You can open an issue per microtask with the title `Review Microtask <num>` in this repository. The body could be empty or contain anything you want to share (pointers to code or documentation, comments, difficulties found) about the microtask. I can help with reviewing the microtasks and suggest some improvements.

Thanks!

**Comment by Rashmi-K-A** [comment]
Hey @vchrombie, I have raised issues for review of the completed microtasks. I will continue to complete more and add issues here as and when I do. Thank you!

**Comment by vchrombie** [comment]
Thank you for the work, let us know if you need any help with the rest of the microtasks.

**Comment by Rashmi-K-A** [comment]
Hey @vchrombie, I was wondering if the mentors could review my proposal. Is that possible?

**Comment by vchrombie** [comment]
> Hey @vchrombie, I was wondering if the mentors could review my proposal. Is that possible?

Hi @Rashmi-K-A, thanks for asking. Maybe you can try mailing them the draft proposal and see if they have any suggestions.

**Comment by Rashmi-K-A** [comment]
Oh, alright, I couldn't find their email IDs on their profile. Is it alright if I leave a comment in the issue thread tagging them?

**Comment by vchrombie** [comment]
Thanks for working on the microtasks, please make sure you submit the proposal on the GSoC website as well as add your entry in the governance repository before the deadline.
